<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <xacro:include filename="gazebo.xacro"/>
    <xacro:include filename="imu.xacro"/>
    <xacro:include filename="transmission.xacro"/>
    <xacro:include filename="left_camera.xacro"/>
    <xacro:include filename="right_camera.xacro"/>

    <!-- <xacro:include filename="realsense-D455.macro.xacro" />
    <xacro:realsense-d455 name="right" parent="base_link" cameras_sequence="a">
        <origin xyz="0.084 0.059 ${0.03+0.105}" rpy="0 0 0" />
    </xacro:realsense-d455>
    <xacro:realsense-d455 name="left" parent="base_link" cameras_sequence="b">
        <origin xyz="0.084 0 ${0.03+0.105}" rpy="0 0 0" />
    </xacro:realsense-d455> -->

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.2" />
    <xacro:property name="base_y_size" value="0.13" />
    <xacro:property name="base_z_size" value="0.1" />
    <xacro:property name="wheelbase" value="0.2"/>
    <xacro:property name="track" value="0.14"/>
    <xacro:property name="base_mass" value="3.0"/>
    <xacro:property name="wheel_length" value="0.01" />
    <xacro:property name="wheel_radius" value="0.045" />

    <!-- BASE LINK -->

    <link name="base_footprint">

    </link>

    <!-- base_link LINK -->

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.045"/>
    </joint>

    <link name="base_link">
        <xacro:inertial_box mass="3" x="${base_x_size}" y="${base_y_size}" z="${base_z_size}">
            <origin xyz="0 0 0.025" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
            <geometry>
                <box size="0.2 0.13 0.05"/>
            </geometry>
            <material name="White">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <!-- WHEEL LINK -->

    <link name="rear_right_wheel_link">
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}1"/>
            </geometry>
            <material name="Black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
    </link>

    <link name="rear_left_wheel_link">
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="Black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
    </link>

    <link name="front_right_wheel_link">
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="Black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
    </link>

    <link name="front_left_wheel_link">
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="Black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>   
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
    </link>

    <link name="right_steering_hinge">
        <xacro:inertial_flip_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_flip_cylinder>
    </link>
    <link name="left_steering_hinge">
        <xacro:inertial_flip_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_flip_cylinder>
    </link>

    <!-- WHEEL JOINT -->

    <joint name="rear_left_wheel" type="continuous">
        <origin xyz="${-wheelbase/2} ${track/2} 0" rpy="-1.57079632679 0 0" />
        <parent link="base_link" />
        <child link="rear_left_wheel_link" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.0" 
            lower="-3.14159265359" 
            upper="3.14159265359" 
            velocity="20.0"
            />
    </joint>

    <joint name="rear_right_wheel" type="continuous">
        <origin xyz="${-wheelbase/2} ${-track/2} 0" rpy="-1.57079632679 0 0" />
        <parent link="base_link" />
        <child link="rear_right_wheel_link" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.0" 
            lower="-3.14159265359" 
            upper="3.14159265359" 
            velocity="20.0"
            />
    </joint>

    <joint name="left_steering_hinge_wheel" type="revolute">
        <origin xyz="${wheelbase/2} ${track/2} 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="left_steering_hinge" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.00" 
            lower="-0.60" 
            upper="0.60" 
            velocity="10.00"/>
    </joint>

    <joint name="front_left_wheel" type="continuous">
        <origin xyz="0 0 0" rpy="-1.57079632679 0 0" />
        <parent link="left_steering_hinge" />
        <child link="front_left_wheel_link" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.0" 
            lower="-3.14159265359" 
            upper="3.14159265359" 
            velocity="20.0"
            />
    </joint>

    <joint name="right_steering_hinge_wheel" type="revolute">
        <origin xyz="${wheelbase/2} ${-track/2} 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="right_steering_hinge" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.00" 
            lower="-0.60" 
            upper="0.60" 
            velocity="10.00"/>
    </joint>

    <joint name="front_right_wheel" type="continuous">
        <origin xyz="0 0 0" rpy="-1.57079632679 0 0" />
        <parent link="right_steering_hinge" />
        <child link="front_right_wheel_link" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.0" 
            lower="-3.14159265359" 
            upper="3.14159265359" 
            velocity="20.0"
            />
    </joint>

    <!-- TRANSMISSIONS -->
    <xacro:wheel_transmission wheel_prefix="left_front"/>
    <xacro:wheel_transmission wheel_prefix="right_front"/>
    <xacro:wheel_transmission wheel_prefix="left_rear"/>
    <xacro:wheel_transmission wheel_prefix="right_rear"/>
    <xacro:steering_hinge_transmission wheel_prefix="left"/>
    <xacro:steering_hinge_transmission wheel_prefix="right"/>

</robot>